package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/yersonargotev/packy/internal/capabilitypack"
)

const generatedNotice = "<!-- Generated by go run ./internal/tools/packdocs. Do not edit. -->\n"

func main() {
	check := flag.Bool("check", false, "verify that committed Pack documentation is current")
	root := flag.String("root", ".", "repository root")
	flag.Parse()
	if flag.NArg() != 0 {
		fail("usage: packdocs [--check] [--root PATH]")
	}

	catalog, err := capabilitypack.Discover(filepath.Join(*root, "bundle"))
	if err != nil {
		fail("discover Pack catalog: %v", err)
	}
	details, err := catalog.ListDetails()
	if err != nil {
		fail("load Pack catalog details: %v", err)
	}
	expected := renderDocumentation(details)
	outputRoot := filepath.Join(*root, "docs", "packs")
	if *check {
		if err := checkDocumentation(outputRoot, expected); err != nil {
			fail("generated Pack documentation is stale: %v", err)
		}
		return
	}
	if err := writeDocumentation(outputRoot, expected); err != nil {
		fail("write generated Pack documentation: %v", err)
	}
}

func renderDocumentation(details []capabilitypack.CatalogDetail) map[string][]byte {
	files := map[string][]byte{"index.md": renderIndex(details)}
	for _, detail := range details {
		files[detail.Pack.ID+".md"] = renderPack(detail)
	}
	return files
}

func renderIndex(details []capabilitypack.CatalogDetail) []byte {
	var out bytes.Buffer
	out.WriteString(generatedNotice)
	out.WriteString("\n# Pack catalog\n\n")
	out.WriteString("This index is generated from the bundled selectable Pack manifests. Use `packy show <pack>` to inspect the same descriptive inventory in the CLI.\n\n")
	for _, detail := range details {
		pack := detail.Pack
		fmt.Fprintf(&out, "- [%s](%s.md) — %s (version `%s`)\n", pack.ID, pack.ID, pack.Description, pack.Version)
	}
	return out.Bytes()
}

func renderPack(detail capabilitypack.CatalogDetail) []byte {
	pack := detail.Pack
	var out bytes.Buffer
	out.WriteString(generatedNotice)
	fmt.Fprintf(&out, "\n# %s Pack\n\n", title(pack.ID))
	out.WriteString("## Purpose\n\n")
	fmt.Fprintf(&out, "%s\n\n", pack.Description)
	fmt.Fprintf(&out, "- Version: `%s`\n", pack.Version)
	fmt.Fprintf(&out, "- Supported surfaces: %s\n", codeList(surfaces(pack.Surfaces)))
	fmt.Fprintf(&out, "- External requirements: %s\n", optionalCodeList(pack.Requires.Tools))

	out.WriteString("\n## Resources\n")
	currentKind := ""
	resources := resourceLookup(pack.Resources)
	for _, inventory := range detail.ResourceInventory {
		if inventory.Resource.Kind != currentKind {
			currentKind = inventory.Resource.Kind
			fmt.Fprintf(&out, "\n### %s\n\n", kindTitle(currentKind))
		}
		fmt.Fprintf(&out, "- `%s` — %s\n", inventory.Resource.ID, inventory.Description)
		fmt.Fprintf(&out, "  - Role: `%s`\n", inventory.Role)
		fmt.Fprintf(&out, "  - Dependencies: %s\n", optionalIdentityList(inventory.Dependencies))
		fmt.Fprintf(&out, "  - Notices: %s\n", optionalIdentityList(inventory.Notices))
		resource := resources[inventory.Resource.Kind+":"+inventory.Resource.ID]
		for _, exclusion := range resource.SurfaceExclusions {
			fmt.Fprintf(&out, "  - %s exclusion (%s): %s\n", title(string(exclusion.Surface)), exclusion.Mode, exclusion.Reason)
		}
		for _, binding := range resource.Bindings {
			if binding.Degradation != "" {
				fmt.Fprintf(&out, "  - %s degradation: `%s`\n", title(string(binding.Surface)), binding.Degradation)
			}
		}
	}

	out.WriteString("\n## Pack exclusions\n\n")
	if len(pack.Contract.Exclusions) == 0 {
		out.WriteString("None.\n")
	} else {
		for _, exclusion := range pack.Contract.Exclusions {
			fmt.Fprintf(&out, "- `%s` — %s\n", exclusion.ID, exclusion.Reason)
		}
	}

	out.WriteString("\n## Inspect and preview\n\n```sh\n")
	fmt.Fprintf(&out, "packy show %s\n", pack.ID)
	fmt.Fprintf(&out, "packy activate %s --surface %s --dry-run\n", pack.ID, pack.Surfaces[0])
	out.WriteString("```\n")
	return out.Bytes()
}

func checkDocumentation(root string, expected map[string][]byte) error {
	entries, err := os.ReadDir(root)
	if err != nil {
		return err
	}
	actual := make(map[string]bool, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".md" {
			return fmt.Errorf("obsolete generated output %s", entry.Name())
		}
		actual[entry.Name()] = true
		want, ok := expected[entry.Name()]
		if !ok {
			return fmt.Errorf("obsolete generated page %s", entry.Name())
		}
		got, err := os.ReadFile(filepath.Join(root, entry.Name()))
		if err != nil {
			return err
		}
		if !bytes.Equal(got, want) {
			return fmt.Errorf("modified generated page %s", entry.Name())
		}
	}
	for name := range expected {
		if !actual[name] {
			return fmt.Errorf("missing generated page %s", name)
		}
	}
	return nil
}

func writeDocumentation(root string, expected map[string][]byte) error {
	if err := os.MkdirAll(root, 0o755); err != nil {
		return err
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if _, keep := expected[entry.Name()]; keep {
			continue
		}
		if entry.IsDir() {
			return fmt.Errorf("refuse to remove unexpected directory %s", entry.Name())
		}
		if err := os.Remove(filepath.Join(root, entry.Name())); err != nil {
			return err
		}
	}
	for name, content := range expected {
		if err := os.WriteFile(filepath.Join(root, name), content, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func resourceLookup(resources []capabilitypack.Resource) map[string]capabilitypack.Resource {
	lookup := make(map[string]capabilitypack.Resource, len(resources))
	for _, resource := range resources {
		lookup[resource.Kind+":"+resource.ID] = resource
	}
	return lookup
}

func optionalIdentityList(identities []capabilitypack.ResourceIdentity) string {
	values := make([]string, len(identities))
	for i, identity := range identities {
		values[i] = identity.Kind + ":" + identity.ID
	}
	return optionalCodeList(values)
}

func optionalCodeList(values []string) string {
	if len(values) == 0 {
		return "None."
	}
	return codeList(values)
}

func codeList(values []string) string {
	quoted := make([]string, len(values))
	for i, value := range values {
		quoted[i] = "`" + value + "`"
	}
	return strings.Join(quoted, ", ")
}

func surfaces(values []capabilitypack.Surface) []string {
	result := make([]string, len(values))
	for i, value := range values {
		result[i] = string(value)
	}
	return result
}

func kindTitle(kind string) string {
	words := strings.Fields(strings.ReplaceAll(kind, "_", " "))
	for i := range words {
		words[i] = title(words[i])
	}
	return strings.Join(words, " ")
}

func title(value string) string {
	if value == "" {
		return value
	}
	return strings.ToUpper(value[:1]) + value[1:]
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
