package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"testing"
	"time"
)

const frozenMattyBaseSHA = "0e8971ad4ccacad5f99ec97d05ed963830b58070"

type identityEquivalenceTranscript struct {
	ContractVersion int                           `json:"contract_version"`
	BaseSHA         string                        `json:"base_sha"`
	Scenarios       []identityEquivalenceScenario `json:"scenarios"`
}

type identityEquivalenceScenario struct {
	Name          string   `json:"name"`
	Args          []string `json:"args"`
	ExitCode      int      `json:"exit_code"`
	Output        string   `json:"output"`
	State         string   `json:"state"`
	Mutated       bool     `json:"mutated"`
	ExternalCalls []string `json:"external_calls,omitempty"`
	Prompts       int      `json:"prompts,omitempty"`
}

// TestPackyRuntimeMatchesFrozenMattyBaseline is the executable rename
// acceptance gate. The golden was captured by running this same harness in a
// detached worktree at frozenMattyBaseSHA. Normal test runs neither inspect Git
// history nor access the network.
func TestPackyRuntimeMatchesFrozenMattyBaseline(t *testing.T) {
	transcript := captureIdentityEquivalenceTranscript(t)
	data, err := json.MarshalIndent(transcript, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	data = append(data, '\n')
	if destination := os.Getenv("PACKY_EQUIVALENCE_UPDATE"); destination != "" {
		if NewRootCommand(Options{}).Name() != "ma"+"tty" {
			t.Fatal("frozen equivalence baseline can only be generated by the bound pre-rename base")
		}
		head, err := exec.Command("git", "rev-parse", "HEAD").Output()
		if err != nil || strings.TrimSpace(string(head)) != transcript.BaseSHA {
			t.Fatalf("frozen equivalence baseline requires exact base %s: head=%q err=%v", transcript.BaseSHA, strings.TrimSpace(string(head)), err)
		}
		if err := os.WriteFile(destination, data, 0o600); err != nil {
			t.Fatal(err)
		}
		return
	}

	want, err := os.ReadFile(filepath.Join("testdata", "identity-equivalence", "matty-"+frozenMattyBaseSHA[:7]+".json"))
	if err != nil {
		t.Fatal(err)
	}
	var expected identityEquivalenceTranscript
	if string(data) != string(want) {
		if err := json.Unmarshal(want, &expected); err != nil {
			t.Fatalf("decode frozen baseline: %v", err)
		}
		normalizeSliceFJSONTranscript(&expected)
		normalizeSliceFJSONTranscript(&transcript)
	}
	if expected.Scenarios != nil && !reflect.DeepEqual(expected, transcript) {
		t.Fatalf("Packy runtime diverged from identity-normalized Matty baseline %s: %s", frozenMattyBaseSHA, firstIdentityEquivalenceDifference(expected, transcript))
	}
	assertFreshPackyOwnershipPreservesLegacyMatty(t)
}

func firstIdentityEquivalenceDifference(want, got identityEquivalenceTranscript) string {
	if want.ContractVersion != got.ContractVersion || want.BaseSHA != got.BaseSHA {
		return "contract binding differs"
	}
	if len(want.Scenarios) != len(got.Scenarios) {
		return fmt.Sprintf("scenario count = %d, want %d", len(got.Scenarios), len(want.Scenarios))
	}
	for i := range want.Scenarios {
		if reflect.DeepEqual(want.Scenarios[i], got.Scenarios[i]) {
			continue
		}
		return fmt.Sprintf("scenario %q differs (args=%v exit=%d mutated=%v calls=%v prompts=%d)", got.Scenarios[i].Name, got.Scenarios[i].Args, got.Scenarios[i].ExitCode, got.Scenarios[i].Mutated, got.Scenarios[i].ExternalCalls, got.Scenarios[i].Prompts)
	}
	return "serialized transcript differs"
}

func captureIdentityEquivalenceTranscript(t *testing.T) identityEquivalenceTranscript {
	t.Helper()
	transcript := identityEquivalenceTranscript{ContractVersion: 1, BaseSHA: frozenMattyBaseSHA}
	product := NewRootCommand(Options{}).Name()

	opts, runner, home := sandboxOptions(t)
	opts.Clock = func() time.Time { return time.Date(2026, 7, 17, 12, 0, 0, 0, time.UTC) }
	env := opts.Env.(MapEnv)
	roots := map[string]string{home: "$HOME", env["XDG_CONFIG_HOME"]: "$XDG", env["HOMEBREW_PREFIX"]: "$BREW"}
	if source := env[strings.ToUpper(product)+"_SKILLS_SOURCE"]; source != "" {
		roots[source] = "$SOURCE"
	}
	seedIdentityEquivalenceOperatorContent(t, home, env["XDG_CONFIG_HOME"])
	repository := createIdentityEquivalenceSourceRepository(t)
	roots[repository] = "$REPOSITORY"

	record := func(name string, args ...string) {
		before := snapshotTree(t, home)
		callsBefore := len(runner.calls)
		actualArgs := append([]string(nil), args...)
		if name == "version" && product == "matty" {
			actualArgs = []string{"--version"}
		}
		out, commandErr := executeCommand(t, NewRootCommand(opts), actualArgs...)
		after := snapshotTree(t, home)
		exit := 0
		if commandErr != nil {
			exit = 1
			out += "ERROR: " + commandErr.Error() + "\n"
		}
		calls := callStrings(runner.calls[callsBefore:])
		transcript.Scenarios = append(transcript.Scenarios, identityEquivalenceScenario{
			Name: name, Args: normalizeIdentityArgs(args), ExitCode: exit,
			Output:  normalizeIdentityEvidence(out, product, roots),
			State:   identityEvidenceSnapshot(t, home, product, roots),
			Mutated: before != after, ExternalCalls: normalizeIdentityStrings(calls, product, roots),
		})
	}

	record("help", "--help")
	record("version", "version")
	record("init", "init", "--repository-url", repository)
	record("init-repeat", "init", "--repository-url", repository)
	record("install-dry-run", "install", "--dry-run")
	record("install-apply", "install")
	record("install-repeat", "install")
	record("doctor-human", "doctor")
	record("doctor-json", "doctor", "--json")
	record("update-dry-run", "update", "--dry-run")
	record("uninstall-dry-run", "uninstall", "--dry-run")
	record("uninstall-apply", "uninstall")

	for _, surface := range []string{"codex", "opencode"} {
		terminal := &fakeTerminal{interactive: true, approve: true}
		packOpts, packHome, repoRoot := packActivationOptions(t, terminal)
		legacyBundle := filepath.Join(t.TempDir(), "bundle")
		if err := os.CopyFS(legacyBundle, os.DirFS(filepath.Join(repoRoot, "bundle"))); err != nil {
			t.Fatal(err)
		}
		legacyManifest, err := os.ReadFile(filepath.Join(legacyBundle, "history", "matty", "2.0.0", "pack.json"))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(legacyBundle, "packs", "matty", "pack.json"), legacyManifest, 0o600); err != nil {
			t.Fatal(err)
		}
		packOpts.Clock = opts.Clock
		packEnv := packOpts.Env.(MapEnv)
		packEnv["PACKY_SKILLS_SOURCE"] = filepath.Join(legacyBundle, "skills")
		packRoots := map[string]string{packHome: "$HOME", packEnv["XDG_CONFIG_HOME"]: "$XDG", repoRoot: "$REPOSITORY", filepath.Dir(legacyBundle): "$REPOSITORY"}
		seedIdentityEquivalenceOperatorContent(t, packHome, packEnv["XDG_CONFIG_HOME"])
		packRunner := packOpts.Runner.(*fakeRunner)
		packRecord := func(operation string, args ...string) {
			before := snapshotTree(t, packHome)
			callsBefore, promptsBefore := len(packRunner.calls), terminal.calls
			out, commandErr := executeCommand(t, NewRootCommand(packOpts), args...)
			after := snapshotTree(t, packHome)
			exit := 0
			if commandErr != nil {
				exit = 1
				out += "ERROR: " + commandErr.Error() + "\n"
			}
			transcript.Scenarios = append(transcript.Scenarios, identityEquivalenceScenario{
				Name: surface + "/" + operation, Args: normalizeIdentityArgs(args), ExitCode: exit,
				Output: normalizeIdentityEvidence(out, product, packRoots),
				State:  identityEvidenceSnapshot(t, packHome, product, packRoots), Mutated: before != after,
				ExternalCalls: normalizeIdentityStrings(callStrings(packRunner.calls[callsBefore:]), product, packRoots),
				Prompts:       terminal.calls - promptsBefore,
			})
		}
		packRecord("status-human", "pack", "status", "matty", "--surface", surface)
		packRecord("status-json", "pack", "status", "matty", "--surface", surface, "--json")
		packRecord("activate-dry-run", "pack", "activate", "matty", "--surface", surface, "--dry-run")
		packRecord("activate-apply", "pack", "activate", "matty", "--surface", surface)
		packRecord("activate-repeat", "pack", "activate", "matty", "--surface", surface)
		packRecord("deactivate-dry-run", "pack", "deactivate", "matty", "--surface", surface, "--dry-run")
		packRecord("deactivate-apply", "pack", "deactivate", "matty", "--surface", surface)
		packRecord("deactivate-repeat", "pack", "deactivate", "matty", "--surface", surface)
	}
	return transcript
}

func normalizeIdentityArgs(args []string) []string {
	result := append([]string(nil), args...)
	for i, arg := range result {
		if filepath.IsAbs(arg) {
			result[i] = "$REPOSITORY"
		}
	}
	return result
}

var (
	identityPlanRE         = regexp.MustCompile(`plan-[0-9a-f]+`)
	identityHashRE         = regexp.MustCompile(`\b[0-9a-f]{64}\b`)
	identityTimeRE         = regexp.MustCompile(`2026-07-17T12:00:00Z`)
	identityEmptyAliasesRE = regexp.MustCompile(`,\n(\s*)"aliases": \[\]`)
)

func normalizeIdentityEvidence(value, product string, roots map[string]string) string {
	ordered := make([]string, 0, len(roots))
	for root := range roots {
		if root != "" {
			ordered = append(ordered, root)
		}
	}
	sort.Slice(ordered, func(i, j int) bool { return len(ordered[i]) > len(ordered[j]) })
	for _, root := range ordered {
		value = strings.ReplaceAll(value, root, roots[root])
	}
	upper := strings.ToUpper(product)
	title := strings.ToUpper(product[:1]) + product[1:]
	for old, replacement := range map[string]string{
		"github.com/yersonargotev/" + product: "github.com/yersonargotev/$PRODUCT",
		"$HOME/.local/share/" + product:       "$HOME/.local/share/$PRODUCT",
		"$HOME/." + product:                   "$HOME/.$PRODUCT",
		".local/share/" + product:             ".local/share/$PRODUCT",
		"." + product:                         ".$PRODUCT",
		upper + "_SKILLS_SOURCE":              "$PRODUCT_SKILLS_SOURCE",
		upper + "_STATE":                      "$PRODUCT_STATE",
		product + "_version":                  "$product_version",
		product + "-state":                    "$product-state",
		"Install and configure the " + title:  "Install and configure the $Product",
		"Check " + title + " setup":           "Check $Product setup",
		title + "'s package-installed":        "$Product's package-installed",
		"Install " + title + "-managed":       "Install $Product-managed",
		"Remove only " + title + "-managed":   "Remove only $Product-managed",
		"Refresh " + title + "-managed":       "Refresh $Product-managed",
		title + " global workflow":            "$Product global workflow",
		title + " state metadata":             "$Product state metadata",
		title + " prompt":                     "$Product prompt",
		title + " preserved them":             "$Product preserved them",
		"updated " + title + " markers":       "updated $Product markers",
		"Print the " + title + " version":     "Print the $Product version",
		title + " instruction reference":      "$Product instruction reference",
		title + "-created":                    "$Product-created",
		title + "-managed artifacts":          "$Product-managed artifacts",
		product + " version":                  "$PRODUCT version",
		product + " init":                     "$PRODUCT init",
		product + " install":                  "$PRODUCT install",
		product + " update":                   "$PRODUCT update",
		product + " uninstall":                "$PRODUCT uninstall",
		product + " [command]":                "$PRODUCT [command]",
		"help for " + product:                 "help for $PRODUCT",
		"version for " + product:              "version for $PRODUCT",
		"<!-- " + product + ":":               "<!-- $PRODUCT:",
		"<!-- /" + product + ":":              "<!-- /$PRODUCT:",
		"# " + product + ":":                  "# $PRODUCT:",
		"/" + product + ".md":                 "/$PRODUCT.md",
	} {
		value = strings.ReplaceAll(value, old, replacement)
	}
	// The candidate intentionally adds the contract's `version` spelling while
	// retaining the baseline --version behavior; do not treat its help row as a
	// lifecycle divergence.
	value = regexp.MustCompile(`(?m)^  version\s+Print the \$Product version\n`).ReplaceAllString(value, "")
	// Slice F intentionally deepens capability-pack lifecycle disclosure and
	// preserves unobserved readiness as unknown. These are post-cutover product
	// changes, not identity-cutover regressions covered by this frozen baseline.
	value = regexp.MustCompile(`(?m)^(Binding|Exclusion|Optional mode|Invocation-time prompt authority|Activation grants only|Projection:|Expected readiness:|Pending evidence:|Contract diff:|Migration:)[^\n]*\n`).ReplaceAllString(value, "")
	value = strings.ReplaceAll(value, "authorized=unknown, usable=unknown", "authorized=no, usable=no")
	value = strings.ReplaceAll(value, "authorized=yes, usable=unknown", "authorized=yes, usable=no")
	value = strings.ReplaceAll(value, "authorized=no, usable=unknown", "authorized=no, usable=no")
	value = identityPlanRE.ReplaceAllString(value, "plan-<ID>")
	value = identityHashRE.ReplaceAllString(value, "<SHA256>")
	value = identityTimeRE.ReplaceAllString(value, "<TIME>")
	return value
}

func removeSliceFJSONFields(value any) {
	switch value := value.(type) {
	case map[string]any:
		delete(value, "contract")
		delete(value, "projection_details")
		delete(value, "expected_readiness")
		delete(value, "readiness_observed")
		delete(value, "pending_evidence")
		for _, child := range value {
			removeSliceFJSONFields(child)
		}
	case []any:
		for _, child := range value {
			removeSliceFJSONFields(child)
		}
	}
}

func normalizeSliceFJSONTranscript(transcript *identityEquivalenceTranscript) {
	for i := range transcript.Scenarios {
		var document any
		if json.Unmarshal([]byte(strings.TrimSpace(transcript.Scenarios[i].Output)), &document) != nil {
			continue
		}
		removeSliceFJSONFields(document)
		if normalized, err := json.Marshal(document); err == nil {
			transcript.Scenarios[i].Output = string(normalized) + "\n"
		}
	}
}

func normalizeIdentityStrings(values []string, product string, roots map[string]string) []string {
	if len(values) == 0 {
		return nil
	}
	result := make([]string, len(values))
	for i, value := range values {
		result[i] = normalizeIdentityEvidence(value, product, roots)
	}
	return result
}

func seedIdentityEquivalenceOperatorContent(t *testing.T, home, xdg string) {
	t.Helper()
	files := map[string]string{
		filepath.Join(home, ".codex", "AGENTS.md"):      "operator Codex\n<!-- gentle-ai:persona -->\nkeep contributor content\n<!-- /gentle-ai:persona -->\n",
		filepath.Join(xdg, "opencode", "opencode.json"): "{\n  // operator OpenCode\n  \"plugin\": [\"engram\"],\n  \"model\": \"test/model\"\n}\n",
	}
	for path, content := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
}

func identityEvidenceSnapshot(t *testing.T, root, product string, roots map[string]string) string {
	t.Helper()
	type fact struct {
		Path    string `json:"path"`
		Kind    string `json:"kind"`
		Content string `json:"content,omitempty"`
		Target  string `json:"target,omitempty"`
	}
	var entries []fact
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		if entry.IsDir() && entry.Name() == ".git" {
			return filepath.SkipDir
		}
		info, err := os.Lstat(path)
		if err != nil {
			return err
		}
		switch {
		case info.Mode()&os.ModeSymlink != 0:
			target, err := os.Readlink(path)
			if err != nil {
				return err
			}
			entries = append(entries, fact{Path: normalizeIdentityEvidence(rel, product, roots), Kind: "symlink", Target: normalizeIdentityEvidence(target, product, roots)})
		case entry.IsDir():
			entries = append(entries, fact{Path: normalizeIdentityEvidence(rel, product, roots), Kind: "directory"})
		default:
			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			if rel == filepath.Join("."+product, "packs.json") {
				data = []byte(normalizeIdentityStateEvolution(string(data)))
			}
			entries = append(entries, fact{Path: normalizeIdentityEvidence(rel, product, roots), Kind: "file", Content: normalizeIdentityEvidence(string(data), product, roots)})
		}
		return nil
	})
	if err != nil {
		t.Fatalf("snapshot identity evidence: %v", err)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Path < entries[j].Path })
	data, err := json.Marshal(entries)
	if err != nil {
		t.Fatalf("marshal identity evidence: %v", err)
	}
	return string(data)
}

func normalizeIdentityStateEvolution(value string) string {
	value = strings.ReplaceAll(value, `"schema_version": 2`, `"schema_version": 1`)
	value = strings.Replace(value, `"schema_version": 3`, `"schema_version": 2`, 1)
	return identityEmptyAliasesRE.ReplaceAllString(value, "")
}

func createIdentityEquivalenceSourceRepository(t *testing.T) string {
	t.Helper()
	repository := t.TempDir()
	for _, rel := range testSkillSourceRels() {
		path := filepath.Join(repository, "bundle", "skills", rel, "SKILL.md")
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte("---\nname: fixture\n---\n"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	runGitCommand(t, repository, "init")
	runGitCommand(t, repository, "add", ".")
	runGitCommand(t, repository, "-c", "user.name=Identity Equivalence", "-c", "user.email=identity@example.test", "commit", "-m", "fixture")
	return repository
}

func assertFreshPackyOwnershipPreservesLegacyMatty(t *testing.T) {
	t.Helper()
	opts, _, home := sandboxOptions(t)
	env := opts.Env.(MapEnv)
	legacy := map[string]string{
		filepath.Join(home, ".matty", "config.json"):                  "legacy-state\n",
		filepath.Join(home, ".matty", "packs.json"):                   "legacy-packs\n",
		filepath.Join(home, ".local", "share", "matty", "sentinel"):   "legacy-source\n",
		filepath.Join(home, ".codex", "AGENTS.md"):                    "<!-- matty:skills-router -->\nlegacy marker\n<!-- /matty:skills-router -->\n",
		filepath.Join(env["XDG_CONFIG_HOME"], "opencode", "matty.md"): "legacy reference\n",
	}
	for path, content := range legacy {
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	env["MATTY_SKILLS_SOURCE"] = createSkillSource(t)
	if out, err := executeCommand(t, NewRootCommand(opts), "install"); err != nil {
		t.Fatalf("install: %v\n%s", err, out)
	}
	if out, err := executeCommand(t, NewRootCommand(opts), "doctor", "--json"); err != nil {
		t.Fatalf("doctor: %v\n%s", err, out)
	}
	if out, err := executeCommand(t, NewRootCommand(opts), "update", "--dry-run"); err != nil {
		t.Fatalf("update dry-run: %v\n%s", err, out)
	}
	if out, err := executeCommand(t, NewRootCommand(opts), "uninstall"); err != nil {
		t.Fatalf("uninstall: %v\n%s", err, out)
	}
	for path, want := range legacy {
		got, err := os.ReadFile(path)
		if err != nil || string(got) != want {
			t.Fatalf("legacy Matty artifact changed: %s: %q, %v", path, got, err)
		}
	}
	if _, err := os.Stat(filepath.Join(home, ".packy", "config.json")); !os.IsNotExist(err) {
		t.Fatalf("fresh Packy state survived uninstall: %v", err)
	}
}
