package gga

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/gentleman-programming/gentle-ai/internal/assets"
	"github.com/gentleman-programming/gentle-ai/internal/components/filemerge"
	"github.com/gentleman-programming/gentle-ai/internal/model"
)

// ggaConfigDir returns the platform-appropriate directory that GGA reads its
// global config from.
//
// On Windows, GGA reads from %APPDATA%\gga (i.e. AppData\Roaming\gga).
// On Linux and macOS, GGA follows the XDG convention and reads from
// ~/.config/gga.
//
// gentle-ai must write to the same location that GGA reads from; using
// %USERPROFILE%\.config on Windows is incorrect and results in `gga config`
// reporting no provider even when the config file was generated.
//
// goos is injected so unit tests can override runtime.GOOS without build tags.
func ggaConfigDir(homeDir string, goos string) string {
	if goos == "windows" {
		appData := os.Getenv("APPDATA")
		if appData == "" {
			// Fallback: APPDATA should always be set on Windows, but guard
			// defensively so we never produce an empty path.
			appData = filepath.Join(homeDir, "AppData", "Roaming")
		}
		return filepath.Join(appData, "gga")
	}
	return filepath.Join(homeDir, ".config", "gga")
}

// InjectionResult describes all files written by the GGA config injection.
type InjectionResult struct {
	ConfigFile    string
	AgentsFile    string
	ConfigChanged bool
	AgentsChanged bool
}

// FilesWritten returns the list of file paths that were written.
func (r InjectionResult) FilesWritten() []string {
	var files []string
	if r.ConfigFile != "" {
		files = append(files, r.ConfigFile)
	}
	if r.AgentsFile != "" {
		files = append(files, r.AgentsFile)
	}
	return files
}

// PostInstallMessages returns user guidance after GGA setup.
func PostInstallMessages() []string {
	return []string{
		"Run `gga install` in any git project to set up the pre-commit hook",
		"Copy `~/.config/gga/AGENTS.md` to your project root and customize it",
	}
}

// ProviderForAgents auto-detects the GGA provider based on selected agents.
// Priority: claude > opencode > gemini > claude (default).
func ProviderForAgents(agentIDs []model.AgentID) string {
	has := make(map[model.AgentID]bool, len(agentIDs))
	for _, id := range agentIDs {
		has[id] = true
	}

	switch {
	case has[model.AgentClaudeCode]:
		return "claude"
	case has[model.AgentOpenCode]:
		return "opencode"
	case has[model.AgentGeminiCLI]:
		return "gemini"
	case has[model.AgentAntigravity]:
		// Antigravity is built on Gemini infrastructure.
		return "gemini"
	case has[model.AgentCodex]:
		return "codex"
	default:
		return "claude"
	}
}

// BuildConfig generates the shell-sourced GGA global config content.
func BuildConfig(provider string) []byte {
	var b strings.Builder
	b.WriteString("# Gentleman Guardian Angel Configuration\n")
	b.WriteString("# Generated by gentle-ai\n")
	b.WriteString("\n")
	b.WriteString("# AI Provider for code review\n")
	b.WriteString("# Options: claude, gemini, codex, opencode, ollama:<model>\n")
	b.WriteString(fmt.Sprintf("PROVIDER=%q\n", provider))
	b.WriteString("\n")
	b.WriteString("# File patterns to review (comma-separated globs)\n")
	b.WriteString("FILE_PATTERNS=\"*.ts,*.tsx,*.js,*.jsx,*.py,*.go\"\n")
	b.WriteString("\n")
	b.WriteString("# Patterns to exclude\n")
	b.WriteString("EXCLUDE_PATTERNS=\"*.test.*,*.spec.*,*.d.ts,dist/*,build/*,node_modules/*\"\n")
	b.WriteString("\n")
	b.WriteString("# Rules file\n")
	b.WriteString("RULES_FILE=\"AGENTS.md\"\n")
	b.WriteString("\n")
	b.WriteString("# Strict mode (fail on ambiguous AI responses)\n")
	b.WriteString("STRICT_MODE=\"true\"\n")
	b.WriteString("\n")
	b.WriteString("# Review timeout in seconds\n")
	b.WriteString("TIMEOUT=\"300\"\n")
	return []byte(b.String())
}

// ConfigPath returns the GGA global config file path.
func ConfigPath(homeDir string) string {
	return filepath.Join(ggaConfigDir(homeDir, runtime.GOOS), "config")
}

// AgentsTemplatePath returns the starter AGENTS.md template path.
func AgentsTemplatePath(homeDir string) string {
	return filepath.Join(ggaConfigDir(homeDir, runtime.GOOS), "AGENTS.md")
}

// Inject writes the GGA global config and starter AGENTS.md template.
// The provider is auto-detected from the selected agents.
func Inject(homeDir string, agentIDs []model.AgentID) (InjectionResult, error) {
	provider := ProviderForAgents(agentIDs)
	configContent := BuildConfig(provider)
	configPath := ConfigPath(homeDir)

	configResult, err := filemerge.WriteFileAtomic(configPath, configContent, 0o644)
	if err != nil {
		return InjectionResult{}, fmt.Errorf("write gga config: %w", err)
	}

	agentsContent, err := assets.Read("gga/AGENTS.md")
	if err != nil {
		return InjectionResult{}, fmt.Errorf("read embedded gga AGENTS.md template: %w", err)
	}

	agentsPath := AgentsTemplatePath(homeDir)
	agentsResult, err := filemerge.WriteFileAtomic(agentsPath, []byte(agentsContent), 0o644)
	if err != nil {
		return InjectionResult{}, fmt.Errorf("write gga AGENTS.md template: %w", err)
	}

	return InjectionResult{
		ConfigFile:    configPath,
		AgentsFile:    agentsPath,
		ConfigChanged: configResult.Changed,
		AgentsChanged: agentsResult.Changed,
	}, nil
}
